#!/usr/bin/env python3
"""Generate firmware/engine/presets.hpp from dbscreamz_lab/static/presets.json

The formants come from presets.json, which is a FROZEN copy of the lab's
(tools/check_engine_copy.py hashes the two against each other), so nothing
new may be added to it. The unison stack below therefore lives here: it is
a pedal-side voicing choice, not lab data.
"""

import json
import sys
from pathlib import Path

# Per-character voice stack, carried by menu 3 knobs 4-6. Ranges mirror the
# lab's controls (voices 1-8, detune 0-60 cents, grain 4-40 ms) and
# firmware/hothouse/param_map.hpp. Wukong keeps the v12 reference stack
# (3 / 11 / 20) so the hero voice still matches the milestone renders; the
# others are voiced by ear from their vocal quality and are meant to be
# re-tuned on hardware.
#
# grain_ms is 20 for every character on purpose: 20 is the value the engine
# has always baked in (FofParams::grain_ms), so making it a stored, knob-
# reachable parameter changes no character's sound. It replaces aspiration,
# which was removed after its two 4-5 kHz sinusoids turned out to be the
# "static" heard on hardware (see the aspiration removal, 2026-09-01).
STACK = {
    'Wukong':  {'unison': 3, 'detune_cents': 11.0, 'grain_ms': 20.0},
    'Rice':    {'unison': 2, 'detune_cents': 8.0,  'grain_ms': 20.0},
    'Prince':  {'unison': 4, 'detune_cents': 18.0, 'grain_ms': 20.0},
    'Piccolo': {'unison': 5, 'detune_cents': 26.0, 'grain_ms': 20.0},
}


def format_float(value):
    """Format float to preserve exact JSON value: 858.4 -> '858.4f'"""
    # Use repr() to preserve precision, then add 'f' suffix
    return repr(float(value)) + 'f'


def read_presets_json():
    """Read presets.json relative to script parent directory"""
    script_dir = Path(__file__).parent.parent
    presets_path = script_dir / 'dbscreamz_lab' / 'static' / 'presets.json'

    with open(presets_path, 'r') as f:
        # Python 3.7+ dicts maintain insertion order, json.load respects it
        return json.load(f)


def generate_header(presets):
    """Generate C++ header content and return (content_string, preset_data_for_verification)"""
    lines = [
        "// presets.hpp (GENERATED by tools/gen_presets.py; do not edit)",
        "#pragma once",
        "struct CharacterPreset {",
        "  const char* name;",
        "  float formants_hz[3];   // baked (tract scale already applied), Hz",
        "  float unison;           // stacked voices, 1..8",
        "  float detune_cents;     // unison spread, 0..60 cents",
        "  float grain_ms;         // FOF grain length, 4..40 ms",
        "};",
        "inline constexpr CharacterPreset kPresets[4] = {",
    ]

    # Collect preset items in JSON key order
    preset_items = []
    for name, data in presets.items():
        formants = data['formants_hz']
        if name not in STACK:
            raise AssertionError(f"{name}: no unison stack entry in gen_presets.py STACK")
        stack = STACK[name]

        # Format each field
        formants_str = ', '.join(format_float(f) for f in formants)

        preset_items.append({
            'name': name,
            'formants': formants,
            'stack': stack,
            'formants_str': formants_str,
            'stack_str': ', '.join(format_float(stack[k]) for k in
                                   ('unison', 'detune_cents', 'grain_ms')),
        })

    # Build preset lines with careful spacing
    for item in preset_items:
        # Format: {"<name>",    {formants}, unison, detune_cents, grain_ms},
        line = f'  {{"{item["name"]}",    {{{item["formants_str"]}}}, {item["stack_str"]}}}'
        # Add comma after all items (including last)
        line += ','
        lines.append(line)

    lines.append("};")
    lines.append("")  # Final newline

    return '\n'.join(lines), preset_items


def verify_roundtrip(presets, preset_items):
    """Verify each emitted number equals its source value exactly"""
    for preset_data, item in zip(presets.values(), preset_items):
        # Check formants
        for i, (json_val, emitted_val) in enumerate(zip(preset_data['formants_hz'], item['formants'])):
            if json_val != emitted_val:
                raise AssertionError(
                    f"{item['name']}: formants[{i}] JSON={json_val} != emitted={emitted_val}"
                )

        # Check the unison stack against STACK, and that it stays in the
        # ranges the menu 3 knobs can reach.
        s = item['stack']
        if s != STACK[item['name']]:
            raise AssertionError(f"{item['name']}: stack {s} != STACK {STACK[item['name']]}")
        if not 1 <= s['unison'] <= 8:
            raise AssertionError(f"{item['name']}: unison {s['unison']} outside 1..8")
        if not 0 <= s['detune_cents'] <= 60:
            raise AssertionError(f"{item['name']}: detune {s['detune_cents']} outside 0..60")
        if not 4 <= s['grain_ms'] <= 40:
            raise AssertionError(f"{item['name']}: grain_ms {s['grain_ms']} outside 4..40")


def main():
    script_dir = Path(__file__).parent.parent
    output_path = script_dir / 'firmware' / 'engine' / 'presets.hpp'

    # Read presets
    presets = read_presets_json()

    # Generate header
    header_content, preset_items = generate_header(presets)

    # Verify roundtrip
    verify_roundtrip(presets, preset_items)

    if '--check' in sys.argv:
        # Check mode: verify file matches
        if not output_path.exists():
            print(f"ERROR: {output_path} does not exist")
            sys.exit(1)
        with open(output_path, 'r') as f:
            existing = f.read()
        if existing != header_content:
            print(f"ERROR: {output_path} does not match generated content")
            sys.exit(1)
        print(f"OK: {output_path} matches generated content")
    else:
        # Write header
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(header_content)
        print(f"Generated: {output_path}")


if __name__ == '__main__':
    main()
