#!/usr/bin/env python3
"""Generate firmware/engine/presets.hpp from dbscreamz_lab/static/presets.json"""

import json
import sys
from pathlib import Path


def format_float(value):
    """Format float to preserve exact JSON value: 858.4 -> '858.4f'"""
    # Use repr() to preserve precision, then add 'f' suffix
    return repr(float(value)) + 'f'


def read_presets_json():
    """Read presets.json relative to script parent directory"""
    script_dir = Path(__file__).parent.parent
    presets_path = script_dir / 'dbscreamz_lab' / 'static' / 'presets.json'

    with open(presets_path, 'r') as f:
        # Python 3.7+ dicts maintain insertion order, json.load respects it
        return json.load(f)


def generate_header(presets):
    """Generate C++ header content and return (content_string, preset_data_for_verification)"""
    lines = [
        "// presets.hpp (GENERATED by tools/gen_presets.py; do not edit)",
        "#pragma once",
        "struct CharacterPreset {",
        "  const char* name;",
        "  float formants_hz[3];   // baked (tract scale already applied), Hz",
        "  float vib_rate_hz;",
        "  float vib_depth_semi;",
        "};",
        "inline constexpr CharacterPreset kPresets[4] = {",
    ]

    # Collect preset items in JSON key order
    preset_items = []
    for name, data in presets.items():
        formants = data['formants_hz']
        vib_rate = data['vib_rate_hz']
        vib_depth = data['vib_depth_semi']

        # Format each field
        formants_str = ', '.join(format_float(f) for f in formants)
        vib_rate_str = format_float(vib_rate)
        vib_depth_str = format_float(vib_depth)

        preset_items.append({
            'name': name,
            'formants': formants,
            'vib_rate': vib_rate,
            'vib_depth': vib_depth,
            'formants_str': formants_str,
            'vib_rate_str': vib_rate_str,
            'vib_depth_str': vib_depth_str,
        })

    # Build preset lines with careful spacing
    for i, item in enumerate(preset_items):
        # Format: {"<name>",    {formants}, vib_rate, vib_depth},
        line = f'  {{"{item["name"]}",    {{{item["formants_str"]}}}, {item["vib_rate_str"]}, {item["vib_depth_str"]}}}'
        # Add comma after all items (including last)
        line += ','
        lines.append(line)

    lines.append("};")
    lines.append("")  # Final newline

    return '\n'.join(lines), preset_items


def verify_roundtrip(presets, preset_items):
    """Verify each emitted number equals JSON value exactly"""
    for preset_data, item in zip(presets.values(), preset_items):
        # Check formants
        for i, (json_val, emitted_val) in enumerate(zip(preset_data['formants_hz'], item['formants'])):
            if json_val != emitted_val:
                raise AssertionError(
                    f"{item['name']}: formants[{i}] JSON={json_val} != emitted={emitted_val}"
                )

        # Check vib_rate
        if preset_data['vib_rate_hz'] != item['vib_rate']:
            raise AssertionError(
                f"{item['name']}: vib_rate_hz JSON={preset_data['vib_rate_hz']} != emitted={item['vib_rate']}"
            )

        # Check vib_depth
        if preset_data['vib_depth_semi'] != item['vib_depth']:
            raise AssertionError(
                f"{item['name']}: vib_depth_semi JSON={preset_data['vib_depth_semi']} != emitted={item['vib_depth']}"
            )


def main():
    script_dir = Path(__file__).parent.parent
    output_path = script_dir / 'firmware' / 'engine' / 'presets.hpp'

    # Read presets
    presets = read_presets_json()

    # Generate header
    header_content, preset_items = generate_header(presets)

    # Verify roundtrip
    verify_roundtrip(presets, preset_items)

    if '--check' in sys.argv:
        # Check mode: verify file matches
        if not output_path.exists():
            print(f"ERROR: {output_path} does not exist")
            sys.exit(1)
        with open(output_path, 'r') as f:
            existing = f.read()
        if existing != header_content:
            print(f"ERROR: {output_path} does not match generated content")
            sys.exit(1)
        print(f"OK: {output_path} matches generated content")
    else:
        # Write header
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(header_content)
        print(f"Generated: {output_path}")


if __name__ == '__main__':
    main()
